spring.application.name=DynamicFormBuilderSystem

spring.datasource.url=jdbc:mysql://localhost:3307/dynamicformsystem?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

springdoc.swagger-ui.path=/docs

spring.jwt.secret=8e0c1567454f4f24a1a601c72278cc0828eccd47b0892b252465f0bf922d5160
spring.jwt.expiration=900000
